#! /bin/bash
# Common stages for both master and worker nodes
# This can be use as user data in launch template or launch configutions


# TO AVOID THE SCRIPT FAILING, RUN IT FROM THE BEGINIG AS ROOT


sudo hostname Knode
sudo swapoff -a
sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

sudo apt update -y
sudo apt-get -y install curl
sudo apt install -y apt-transport-https -y

sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

sudo cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
sudo apt update -y
sudo apt install -y kubelet kubeadm  containerd kubectl
# apt-mark hold will prevent the package from being automatically upgraded or removed.

sudo apt-mark hold kubelet kubeadm kubectl containerd

sudo cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

sudo cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF

sudo sysctl --system
sudo mkdir -p /etc/containerd
sudo containerd config default | sudo tee /etc/containerd/config.toml
sudo systemctl restart containerd

# Enable and start kubelet service
sudo systemctl daemon-reload
sudo systemctl start kubelet
sudo systemctl enable kubelet.service

# Last step will be to run the kubeadmin join command line from the master 
# to be added to the cluster as worker. it will be of the following form
# kubeadm join 172.31.27.179:6443 --token lxpzgb.ewm454pnfkf9l526 --discovery-token-ca-cert-hash sha256:e2d07e4e81939fbf082183965361740f2c912d4495a6c02e6da17af428298d29

# In case the worker node is restarted and the IP changes, the join the cluster again, some services need to be restarted 
sudo systemctl daemon-stop
sudo rm -f /etc/kubernetes/pki/ca.crt
sudo rm -f /etc/kubernetes/kubelet.conf
sudo systemctl stop kubelet
sudo systemctl stop kubelet.service
systemctl stop containerd
sudo systemctl start kubelet
sudo systemctl start kubelet.service
systemctl restart containerd
# then run the kubeadm join command from the master again
